import { Telemetry } from '../domain/telemetry.model.js';

const referenceTime = Date.now();

const minutesAgo = (minutes: number): Date =>
  new Date(referenceTime - minutes * 60_000);

export const telemetry: Telemetry[] = [
  // Environmental sensor: low recent battery reading
  {
    id: 'tel-env-001',
    deviceId: 'env-sensor-001',
    metric: 'batteryLevel',
    value: 18,
    unit: '%',
    timestamp: minutesAgo(180),
  },
  {
    id: 'tel-env-002',
    deviceId: 'env-sensor-001',
    metric: 'batteryLevel',
    value: 12,
    unit: '%',
    timestamp: minutesAgo(20),
  },
  {
    id: 'tel-env-003',
    deviceId: 'env-sensor-001',
    metric: 'temperature',
    value: 21.4,
    unit: '°C',
    timestamp: minutesAgo(60),
  },
  {
    id: 'tel-env-004',
    deviceId: 'env-sensor-001',
    metric: 'temperature',
    value: 21.8,
    unit: '°C',
    timestamp: minutesAgo(15),
  },
  {
    id: 'tel-env-005',
    deviceId: 'env-sensor-001',
    metric: 'humidity',
    value: 48,
    unit: '%',
    timestamp: minutesAgo(15),
  },

  // Water-quality sensor: abnormal recent pH and elevated turbidity
  {
    id: 'tel-water-001',
    deviceId: 'water-sensor-001',
    metric: 'ph',
    value: 7.2,
    timestamp: minutesAgo(180),
  },
  {
    id: 'tel-water-002',
    deviceId: 'water-sensor-001',
    metric: 'ph',
    value: 9.1,
    timestamp: minutesAgo(10),
  },
  {
    id: 'tel-water-003',
    deviceId: 'water-sensor-001',
    metric: 'turbidity',
    value: 2.1,
    unit: 'NTU',
    timestamp: minutesAgo(180),
  },
  {
    id: 'tel-water-004',
    deviceId: 'water-sensor-001',
    metric: 'turbidity',
    value: 6.8,
    unit: 'NTU',
    timestamp: minutesAgo(10),
  },
  {
    id: 'tel-water-005',
    deviceId: 'water-sensor-001',
    metric: 'temperature',
    value: 17.9,
    unit: '°C',
    timestamp: minutesAgo(10),
  },

  // Industrial sensor: rising vibration and high temperature
  {
    id: 'tel-vibration-001',
    deviceId: 'vibration-sensor-001',
    metric: 'vibration',
    value: 2.4,
    unit: 'mm/s',
    timestamp: minutesAgo(120),
  },
  {
    id: 'tel-vibration-002',
    deviceId: 'vibration-sensor-001',
    metric: 'vibration',
    value: 8.9,
    unit: 'mm/s',
    timestamp: minutesAgo(25),
  },
  {
    id: 'tel-vibration-003',
    deviceId: 'vibration-sensor-001',
    metric: 'temperature',
    value: 63.2,
    unit: '°C',
    timestamp: minutesAgo(120),
  },
  {
    id: 'tel-vibration-004',
    deviceId: 'vibration-sensor-001',
    metric: 'temperature',
    value: 92.4,
    unit: '°C',
    timestamp: minutesAgo(25),
  },

  // Asset tracker: weak recent signal
  {
    id: 'tel-tracker-001',
    deviceId: 'asset-tracker-001',
    metric: 'signalStrength',
    value: -87,
    unit: 'dBm',
    timestamp: minutesAgo(150),
  },
  {
    id: 'tel-tracker-002',
    deviceId: 'asset-tracker-001',
    metric: 'signalStrength',
    value: -112,
    unit: 'dBm',
    timestamp: minutesAgo(12),
  },
  {
    id: 'tel-tracker-003',
    deviceId: 'asset-tracker-001',
    metric: 'batteryLevel',
    value: 68,
    unit: '%',
    timestamp: minutesAgo(150),
  },
  {
    id: 'tel-tracker-004',
    deviceId: 'asset-tracker-001',
    metric: 'batteryLevel',
    value: 64,
    unit: '%',
    timestamp: minutesAgo(12),
  },
  {
    id: 'tel-tracker-005',
    deviceId: 'asset-tracker-001',
    metric: 'speed',
    value: 0,
    unit: 'km/h',
    timestamp: minutesAgo(12),
  },

  // Temperature sensor: normal telemetry
  {
    id: 'tel-temperature-001',
    deviceId: 'temperature-sensor-001',
    metric: 'temperature',
    value: 4.1,
    unit: '°C',
    timestamp: minutesAgo(90),
  },
  {
    id: 'tel-temperature-002',
    deviceId: 'temperature-sensor-001',
    metric: 'temperature',
    value: 4.3,
    unit: '°C',
    timestamp: minutesAgo(8),
  },
  {
    id: 'tel-temperature-003',
    deviceId: 'temperature-sensor-001',
    metric: 'humidity',
    value: 52,
    unit: '%',
    timestamp: minutesAgo(8),
  },
  {
    id: 'tel-temperature-004',
    deviceId: 'temperature-sensor-001',
    metric: 'batteryLevel',
    value: 91,
    unit: '%',
    timestamp: minutesAgo(8),
  },

  // Weather station: normal environmental readings
  {
    id: 'tel-weather-001',
    deviceId: 'weather-station-001',
    metric: 'temperature',
    value: 15.8,
    unit: '°C',
    timestamp: minutesAgo(75),
  },
  {
    id: 'tel-weather-002',
    deviceId: 'weather-station-001',
    metric: 'temperature',
    value: 16.2,
    unit: '°C',
    timestamp: minutesAgo(5),
  },
  {
    id: 'tel-weather-003',
    deviceId: 'weather-station-001',
    metric: 'humidity',
    value: 67,
    unit: '%',
    timestamp: minutesAgo(5),
  },
  {
    id: 'tel-weather-004',
    deviceId: 'weather-station-001',
    metric: 'pressure',
    value: 1013.2,
    unit: 'hPa',
    timestamp: minutesAgo(5),
  },
  {
    id: 'tel-weather-005',
    deviceId: 'weather-station-001',
    metric: 'batteryLevel',
    value: 76,
    unit: '%',
    timestamp: minutesAgo(5),
  },

  // Energy meter: stable electrical measurements
  {
    id: 'tel-energy-001',
    deviceId: 'energy-meter-001',
    metric: 'voltage',
    value: 230.5,
    unit: 'V',
    timestamp: minutesAgo(70),
  },
  {
    id: 'tel-energy-002',
    deviceId: 'energy-meter-001',
    metric: 'voltage',
    value: 229.8,
    unit: 'V',
    timestamp: minutesAgo(6),
  },
  {
    id: 'tel-energy-003',
    deviceId: 'energy-meter-001',
    metric: 'current',
    value: 4.2,
    unit: 'A',
    timestamp: minutesAgo(70),
  },
  {
    id: 'tel-energy-004',
    deviceId: 'energy-meter-001',
    metric: 'current',
    value: 4.7,
    unit: 'A',
    timestamp: minutesAgo(6),
  },
  {
    id: 'tel-energy-005',
    deviceId: 'energy-meter-001',
    metric: 'power',
    value: 1080,
    unit: 'W',
    timestamp: minutesAgo(6),
  },
];
